version: 0.0
os: linux
files:
  - source: files/test-config.txt
    destination: /tmp/test-deployment/
  - source: files/test-script.sh
    destination: /tmp/test-deployment/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
